blank_issues_enabled: false
contact_links:
  - name: â“ Usage question
    url: https://github.com/xarray-contrib/xbatcher/discussions
    about: |
      Ask questions and discuss with other community members here.
